from django.urls import path
from django.views.generic import DetailView

from zmiany_aranz.models import Premises

from zmiany_aranz.views import (
    IndexView,
    ProcedureDetailView,
    ProcedureSubpagesListView,
    ProcedureSubpagesCreateView,
    ProcedureSubpagesUpdateView,
    ProcedureSubpagesDeleteView,
    CustomerOfProcedureCreateView,
    CustomerOfProcedureUpdateView,
    CustomerOfProcedureDeleteView,
    CustomerCreateView,
    CustomerDetailView,
    CustomerUpdateView,
    CustomerDeleteView,
    SendEmailView,
    PremisesImportView,
    PremisesSymbolRedirectView,
)

from .models import (
    Premises,
    Cost,
    Invoice,
    CustomerOfProcedure,
    CostEstimate,
)

app_name = "zmiany_aranz"
APP_NAME = app_name

urlpatterns = [
    path(
        "",
        IndexView.as_view(),
        name="index",
    ),
    path(
        "procedure/<int:pk>/",
        ProcedureDetailView.as_view(),
        name="procedure_detail_view",
    ),
    path(
        "procedure/<int:pk>/cost/list/",
        ProcedureSubpagesListView.as_view(
            model=Cost,
            template_name=f"{APP_NAME}/procedure_costs_list.html",
        ),
        name="procedure_costs_list",
    ),
    path(
        "procedure/<int:pk>/cost/add/",
        ProcedureSubpagesCreateView.as_view(
            model=Cost,
            fields="__all__",
            template_name=f"{APP_NAME}/procedure_cost_create.html",
            success_url_name="procedure_costs_list",
            related_field_name="costs",
        ),
        name="procedure_cost_create",
    ),
    path(
        "cost/<int:pk>/update/",
        ProcedureSubpagesUpdateView.as_view(
            model=Cost,
            fields="__all__",
            template_name=f"{APP_NAME}/cost_update.html",
            success_url_name="procedure_costs_list",
        ),
        name="cost_update",
    ),
    path(
        "cost/<int:pk>/delete/",
        ProcedureSubpagesDeleteView.as_view(
            model=Cost,
            template_name=f"{APP_NAME}/cost_delete_confirm.html",
            success_url_name="procedure_costs_list",
        ),
        name="cost_delete",
    ),
    path(
        "procedure/<int:pk>/cost_estimate/list/",
        ProcedureSubpagesListView.as_view(
            model=CostEstimate,
            template_name=f"{APP_NAME}/procedure_cost_estimates_list.html",
        ),
        name="procedure_cost_estimates_list",
    ),
    path(
        "procedure/<int:pk>/cost_estimate/add/",
        ProcedureSubpagesCreateView.as_view(
            model=CostEstimate,
            fields="__all__",
            template_name=f"{APP_NAME}/procedure_cost_estimate_create.html",
            success_url_name="procedure_cost_estimates_list",
            related_field_name="cost_estimates",
        ),
        name="procedure_cost_estimate_create",
    ),
    path(
        "cost_estimate/<int:pk>/update/",
        ProcedureSubpagesUpdateView.as_view(
            model=CostEstimate,
            fields="__all__",
            template_name=f"{APP_NAME}/cost_estimate_update.html",
            success_url_name="procedure_cost_estimates_list",
        ),
        name="cost_estimate_update",
    ),
    path(
        "cost_estimate/<int:pk>/delete/",
        ProcedureSubpagesDeleteView.as_view(
            model=CostEstimate,
            template_name=f"{APP_NAME}/cost_estimate_delete_confirm.html",
            success_url_name="procedure_cost_estimates_list",
        ),
        name="cost_estimate_delete",
    ),
    path(
        "procedure/<int:pk>/invoice/list/",
        ProcedureSubpagesListView.as_view(
            model=Invoice,
            template_name=f"{APP_NAME}/procedure_invoices_list.html",
        ),
        name="procedure_invoices_list",
    ),
    path(
        "procedure/<int:pk>/invoice/add/",
        ProcedureSubpagesCreateView.as_view(
            model=Invoice,
            fields="__all__",
            template_name=f"{APP_NAME}/procedure_invoice_create.html",
            success_url_name="procedure_invoices_list",
            related_field_name="invoices",
        ),
        name="procedure_invoice_create",
    ),
    path(
        "invoice/<int:pk>/update/",
        ProcedureSubpagesUpdateView.as_view(
            model=Invoice,
            fields="__all__",
            template_name=f"{APP_NAME}/invoice_update.html",
            success_url_name="procedure_invoices_list",
        ),
        name="invoice_update",
    ),
    path(
        "invoice/<int:pk>/delete/",
        ProcedureSubpagesDeleteView.as_view(
            model=Invoice,
            template_name=f"{APP_NAME}/invoice_delete_confirm.html",
            success_url_name="procedure_invoices_list",
        ),
        name="invoice_delete",
    ),
    path(
        "procedure/<int:pk>/customer/list/",
        ProcedureSubpagesListView.as_view(
            model=CustomerOfProcedure,
            template_name=f"{APP_NAME}/procedure_customers_list.html",
        ),
        name="procedure_customers_list",
    ),
    path(
        "procedure/<int:pk>/customer/add/",
        CustomerOfProcedureCreateView.as_view(),
        name="customer_of_procedure_create",
    ),
    path(
        "customer_of_procedure/<int:pk>/update/",
        CustomerOfProcedureUpdateView.as_view(),
        name="customer_of_procedure_update",
    ),
    path(
        "customer_of_procedure/<int:pk>/delete/",
        CustomerOfProcedureDeleteView.as_view(),
        name="customer_of_procedure_delete",
    ),
    path(
        "customer/create/",
        CustomerCreateView.as_view(),
        name="customer_create",
    ),
    path(
        "customer/<int:pk>/",
        CustomerDetailView.as_view(),
        name="customer_detail",
    ),
    path(
        "customer/<int:pk>/update/",
        CustomerUpdateView.as_view(),
        name="customer_update",
    ),
    path(
        "customer/<int:pk>/delete/",
        CustomerDeleteView.as_view(),
        name="customer_delete",
    ),
    path(
        "procedure/<int:pk>/send_email/<slug:slug>/",
        SendEmailView.as_view(),
        name="send_email",
    ),
    path(
        "premises-import/",
        PremisesImportView.as_view(),
        name="premises_import",
    ),
    path(
        "premises/<int:pk>/",
        DetailView.as_view(
            model=Premises, template_name="zmiany_aranz/premises_detail.html"
        ),
        name="premises_detail",
    ),
    path(
        "premises-redirect/",
        PremisesSymbolRedirectView.as_view(),
        name="premises_redirect",
    ),
]
