from django.urls import path
from zmiany_aranz.views import (
    IndexView,
    ProcedureDetailView,
    ProcedureCostsList,
    CostCreateView,
    CostUpdateView,
    CostDeleteView,
    ProcedureCostEstimatesList,
    CostEstimateCreateView,
    CostEstimateUpdateView,
    CostEstimateDeleteView,
    ProcedureInvoicesList,
    InvoiceCreateView,
    InvoiceUpdateView,
    InvoiceDeleteView,
    ProcedureCustomersList,
    CustomerOfProcedureCreateView,
    CustomerOfProcedureUpdateView,
    CustomerOfProcedureDeleteView,
    CustomerCreateView,
    CustomerDetailView,
    CustomerUpdateView,
    CustomerDeleteView,
    SendEmailView,
    PremisesImportView,
)

app_name = "zmiany_aranz"

urlpatterns = [
    path(
        "",
        IndexView.as_view(),
        name="index",
    ),
    path(
        "procedure/<int:pk>/",
        ProcedureDetailView.as_view(),
        name="procedure_detail_view",
    ),
    path(
        "procedure/<int:pk>/cost/list/",
        ProcedureCostsList.as_view(),
        name="procedure_costs_list",
    ),
    path(
        "procedure/<int:pk>/cost/add/",
        CostCreateView.as_view(),
        name="procedure_cost_create",
    ),
    path(
        "cost/<int:pk>/update/",
        CostUpdateView.as_view(),
        name="cost_update",
    ),
    path(
        "cost/<int:pk>/delete/",
        CostDeleteView.as_view(),
        name="cost_delete",
    ),
    path(
        "procedure/<int:pk>/cost_estimate/list/",
        ProcedureCostEstimatesList.as_view(),
        name="procedure_cost_estimates_list",
    ),
    path(
        "procedure/<int:pk>/cost_estimate/add/",
        CostEstimateCreateView.as_view(),
        name="procedure_cost_estimate_create",
    ),
    path(
        "cost_estimate/<int:pk>/update/",
        CostEstimateUpdateView.as_view(),
        name="cost_estimate_update",
    ),
    path(
        "cost_estimate/<int:pk>/delete/",
        CostEstimateDeleteView.as_view(),
        name="cost_estimate_delete",
    ),
    path(
        "procedure/<int:pk>/invoice/list/",
        ProcedureInvoicesList.as_view(),
        name="procedure_invoices_list",
    ),
    path(
        "procedure/<int:pk>/invoice/add/",
        InvoiceCreateView.as_view(),
        name="procedure_invoice_create",
    ),
    path(
        "invoice/<int:pk>/update/",
        InvoiceUpdateView.as_view(),
        name="invoice_update",
    ),
    path(
        "invoice/<int:pk>/delete/",
        InvoiceDeleteView.as_view(),
        name="invoice_delete",
    ),
    path(
        "procedure/<int:pk>/customer/list/",
        ProcedureCustomersList.as_view(),
        name="procedure_customers_list",
    ),
    path(
        "procedure/<int:pk>/customer/add/",
        CustomerOfProcedureCreateView.as_view(),
        name="customer_of_procedure_create",
    ),
    path(
        "customer_of_procedure/<int:pk>/update/",
        CustomerOfProcedureUpdateView.as_view(),
        name="customer_of_procedure_update",
    ),
    path(
        "customer_of_procedure/<int:pk>/delete/",
        CustomerOfProcedureDeleteView.as_view(),
        name="customer_of_procedure_delete",
    ),
    path(
        "customer/create/",
        CustomerCreateView.as_view(),
        name="customer_create",
    ),
    path(
        "customer/<int:pk>/",
        CustomerDetailView.as_view(),
        name="customer_detail",
    ),
    path(
        "customer/<int:pk>/update/",
        CustomerUpdateView.as_view(),
        name="customer_update",
    ),
    path(
        "customer/<int:pk>/delete/",
        CustomerDeleteView.as_view(),
        name="customer_delete",
    ),
    path(
        "procedure/<int:pk>/send_email/<slug:slug>/",
        SendEmailView.as_view(),
        name="send_email",
    ),
    path(
        "premises-import/",
        PremisesImportView.as_view(),
        name="premises_import",
    ),
]
