# Generated by Django 4.1.4 on 2023-01-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zmiany_aranz", "0003_alter_customerofprocedure_shares"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
