# Generated by Django 4.1.4 on 2023-01-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zmiany_aranz", "0004_alter_invoice_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="procedure",
            name="customers",
            field=models.ManyToManyField(
                blank=True,
                related_name="procedures",
                through="zmiany_aranz.CustomerOfProcedure",
                to="zmiany_aranz.customer",
            ),
        ),
    ]
