# Generated by Django 4.1.4 on 2023-01-21 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zmiany_aranz", "0005_alter_procedure_customers"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("mail_subject", models.CharField(max_length=100)),
                ("mail_body", models.TextField()),
                ("mail_attachments", models.TextField()),
                ("is_template", models.BooleanField(default=False)),
                ("slug", models.SlugField(editable=False)),
                (
                    "investment_stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zmiany_aranz.investmentstage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvestmentStagePerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "investment_stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zmiany_aranz.investmentstage",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zmiany_aranz.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "InvestmentStagePerson",
                "verbose_name_plural": "InvestmentStagePersons",
            },
        ),
        migrations.CreateModel(
            name="EmailActionPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.IntegerField(choices=[(1, "TO"), (2, "CC"), (3, "BCC")]),
                ),
                (
                    "email_action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zmiany_aranz.emailaction",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zmiany_aranz.person",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="emailaction",
            name="persons",
            field=models.ManyToManyField(
                through="zmiany_aranz.EmailActionPerson", to="zmiany_aranz.person"
            ),
        ),
        migrations.AddField(
            model_name="investmentstage",
            name="persons",
            field=models.ManyToManyField(
                blank=True,
                through="zmiany_aranz.InvestmentStagePerson",
                to="zmiany_aranz.person",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="emailaction",
            unique_together={("investment_stage", "slug")},
        ),
    ]
