# Generated by Django 4.1.4 on 2023-01-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "zmiany_aranz",
            "0006_emailaction_investmentstageperson_emailactionperson_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailaction",
            name="mail_attachments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="emailaction",
            name="mail_body",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="emailaction",
            name="mail_subject",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
