# Generated by Django 4.1.4 on 2023-01-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Signature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.FilePathField(blank=True, null=True)),
                ("text", models.TextField(blank=True, null=True)),
                ("default", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Signature",
                "verbose_name_plural": "Signatures",
            },
        ),
    ]
