# Generated by Django 4.1.4 on 2023-01-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outlook", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="signature",
            name="name",
            field=models.CharField(default="a", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="signature",
            name="path",
            field=models.FilePathField(
                blank=True,
                match=".*\\.txt",
                null=True,
                path="D:\\Users\\gswitek\\AppData\\Roaming\\Microsoft\\Signatures",
            ),
        ),
    ]
