# Generated by Django 4.1.4 on 2023-01-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outlook", "0002_signature_name_alter_signature_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signature",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
